import { StyleSheet } from "react-native";
import { theme } from "../../styles/theme";

export const authStyles = StyleSheet.create({
  form: {
    marginTop: 15,
  },
  title: {
    color: theme.yellow,
  },
  inputWrapper: {
    display: "flex",
    flexDirection: "row",
    marginTop: 17,
  },
  icon: {
    width: "14%",
    height: 41,
    position: "relative",
    overflow: "hidden",
  },
  iconWrapper: {
    height: 41,
    width: "100%",
    borderWidth: 1,
    borderColor: theme.yellow,
    backgroundColor: theme.yellow,
    zIndex: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  iconDecoration: {
    position: "absolute",
    top: -11,
    left: -11,
    width: 22,
    height: 22,
    transform: [{ rotate: "45deg" }],
    backgroundColor: theme.black,
    borderWidth: 1,
    borderColor: theme.yellow,
    zIndex: 2,
  },
  inputContent: {
    width: "86%",
    position: "relative",
    overflow: "hidden",
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: theme.yellow,
    fontSize: 20,
    height: 41,
    paddingLeft: 7,
    paddingRight: 7,
    zIndex: 0,
    color: "#fff",
  },
  inputDecoration: {
    position: "absolute",
    bottom: -11,
    right: -11,
    width: 22,
    height: 22,
    transform: [{ rotate: "45deg" }],
    backgroundColor: theme.black,
    borderWidth: 1,
    borderColor: theme.yellow,
    zIndex: 2,
  },
  buttonWrapper: {
    position: "relative",
    marginTop: 24,
    overflow: "hidden",
  },
  buttonDecorationLeft: {
    position: "absolute",
    top: -11,
    right: -11,
    width: 22,
    height: 22,
    transform: [{ rotate: "45deg" }],
    backgroundColor: theme.black,
    borderWidth: 1,
    borderColor: theme.yellow,
    zIndex: 2,
  },
  buttonDecorationRight: {
    position: "absolute",
    bottom: -11,
    left: -11,
    width: 22,
    height: 22,
    transform: [{ rotate: "45deg" }],
    backgroundColor: theme.black,
    borderWidth: 1,
    borderColor: theme.yellow,
    zIndex: 2,
  },
  button: {
    height: 41,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#fff",
    backgroundColor: theme.yellow,
    zIndex: 0,
  },
  buttonText: {
    fontSize: 24,
    color: theme.black,
    fontWeight: "700",
    letterSpacing: 3,
  },
  errorWrapper: {
    position: "relative",
    marginTop: 24,
    overflow: "hidden",
  },
  errorText: {
    backgroundColor: theme.errorRed,
    color: "#fff",
    fontWeight: "bold",
    letterSpacing: 2,
    fontSize: 18,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 13,
    paddingRight: 13,
    borderWidth: 1,
    borderColor: theme.bloodRed,
  },
  errorDecorationRight: {
    position: "absolute",
    bottom: -11,
    left: -11,
    width: 22,
    height: 22,
    transform: [{ rotate: "45deg" }],
    backgroundColor: theme.black,
    borderWidth: 1,
    borderColor: theme.bloodRed,
    zIndex: 2,
  },
  errorDecorationLineRightSecond: {
    position: "absolute",
    height: "80%",
    width: 3,
    bottom: 0,
    right: 28,
    backgroundColor: theme.black,
  },
  errorDecorationLineRight: {
    position: "absolute",
    height: "80%",
    width: 3,
    top: 0,
    right: 16,
    backgroundColor: theme.black,
  },
});
